services:
  identity-service-backend-database:
    image: postgres:17-alpine
    restart: always
    container_name: identity-service-backend-database
    ports:
      - "${POSTGRES_HOST_PORT:-7401}:5432"
    env_file:
      - .env
    volumes:
      - ./data/pg:/var/lib/postgresql/data
  identity-service-backend:
    build: .
    container_name: identity-service-backend
    restart: always
    ports:
      - "1139:${PORT-3000}"
    depends_on:
      - identity-service-backend-database
    env_file:
      - .env
